#!/bin/sh

CURWDIR="$(cd $(dirname $0) && pwd)"
TITLE="定時任務"
PROGRAM_NAME="ppht-timer"
# CUSTOM_BIN="/system/apps/tp/bin/custom"
# CUSTOM_CONFIG_FILE="$CURWDIR/custom.conf"

APPS_CONFIG_DIR="/data/conf"
LAUNCHER_CONFIG_DIR="$APPS_CONFIG_DIR/launcher/conf.d"
LAUNCHER_CONFIG_FILE="$LAUNCHER_CONFIG_DIR/$PROGRAM_NAME.conf"

ICON="res/icon_normal.png"
PRESSED_ICON="res/icon_pressed.png"

# PID_FILE="$CURWDIR/$PROGRAM_NAME.pid"
# PKILL_BIN="/usr/bin/pkill"
INSTALL_BIN="/usr/bin/install"
REMOVE="/bin/rm -f"
# LUA_BIN="/system/bin/lua"
# LUA_SCRIPT_PATH="/system/share/lua/5.1/tp_entry.lua"

# INTERVAL="$CURWDIR/interval.conf";

usage() {
    echo "ERROR: action missing"
    echo "syntax: $0 <start|stop|restart|status|config|install|uninstall>"
    echo "example: $0 start"
}

start() {
    echo "not implemented"
}

stop() {
    echo "not implemented"
}

install() 
{
    echo "{" > "$PROGRAM_NAME.conf"
    echo "\"name\" :  \"$TITLE\"," >> "$PROGRAM_NAME.conf"
    echo "\"icon\" : \"$CURWDIR/$ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"iconPressed\" : \"$CURWDIR/$PRESSED_ICON\"," >> "$PROGRAM_NAME.conf"
    echo "\"exec\" : \"$CURWDIR/init start\"," >> "$PROGRAM_NAME.conf"
    echo "\"msgNum\" : 4" >> "$PROGRAM_NAME.conf"
    echo "}" >> "$PROGRAM_NAME.conf"

    $INSTALL_BIN -d $LAUNCHER_CONFIG_DIR
    $INSTALL_BIN "$PROGRAM_NAME.conf" "$LAUNCHER_CONFIG_FILE"
}



uninstall() {
    $REMOVE "$LAUNCHER_CONFIG_FILE"
}

config() {
    echo "not implemented"
}

status() {
    echo "not implemented"
}

# main
if [ $# -lt 1 ]; then
    usage
    exit 255
fi

# start       : 启动，实现启动本应用的操作
# stop        : 停止， 停止本应用的操作
# status      : 查询状态，查询本应用的状态
# set_config  : 对本应用重新进行配置，生效配置数据应该进行的操作
# install     : 安装，本应用安装后的一次性操作
# uninstall   : 卸载，本应用被卸载前的一次性操作
case "$1" in
    "start" )
        start;;
    "stop" )
        stop;;
    "restart" )
        start
        stop;;
    "install" )
        install;;
    "uninstall" )
        uninstall;;
    "config" )
    	config;;
    "status" )
    	status;;
    * )
        usage ;;
esac
